# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "andrew-stclair"
    reviewers:
      - "andrew-stclair"
      
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - "andrew-stclair"
    reviewers:
      - "andrew-stclair"

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - "andrew-stclair"
    reviewers:
      - "andrew-stclair"
