name: Build and Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build 11ty
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm fund
          npx @11ty/eleventy --input=src --output=build --config=src/.eleventy.js

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ github.repository }}:latest
          pull: true
