name: Pull Request Vulnerability Scan
on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Build 11ty
        run: |
          npm install --global @11ty/eleventy --unsafe-perm
          cd $GITHUB_WORKSPACE
          npx @11ty/eleventy --input=src --output=build --config=src/.eleventy.js

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-mr
          pull: true

    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/${{ github.repository }}:latest-mr
