name: PR Scan
on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build 11ty
        run: |
          npm install --global @11ty/eleventy --unsafe-perm
          cd $GITHUB_WORKSPACE
          npx @11ty/eleventy --input=src --output=build --config=src/.eleventy.js
          
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }} .

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
          args: --file=Dockerfile

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
