name: Build and Publish
on:
  pull_request:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: none
  statuses: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      
      - name: Build 11ty
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm fund
          npx @11ty/eleventy --input=src --output=build --config=src/.eleventy.js
          
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=site_size::$(du -sh build)"

      - name: Comment on PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: '${{ steps.vars.outputs.site_size }} size'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
