name: Vulnerability Scan
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-18.04
    steps:          
      - name: Vulnerability Scan
        uses: azure/container-scan@v0
        with:
          image-name: ghcr.io/${{ github.repository }}:latest
          severity-threshold: LOW
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
